services:
  - type: web
    name: shorturl-api
    runtime: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_DATA_REDIS_URL
        sync: false
      - key: SYSTEM_URL
        sync: false
    healthCheckPath: /actuator/health
