spring.application.name=shorturl

server.port=8080

# PostgreSQL Database từ Render
spring.datasource.url=jdbc:postgresql://dpg-d8c1ba77f7va7df7d7hg-a:5432/roadtosemv_db
spring.datasource.username=roadtosemv_db_user
spring.datasource.password=BVbwazavbLJhUmUzlH54OEwm5e6Pp8j
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis từ Render
spring.data.redis.url=rediss://red-d860bl8js32c73ar6gqg:jSqcimbrK3Ik8zzkWHXpsLuqCFHJVWop@singapore-keyvalue.render.com:6379

system.url=localhost:8080/

# Actuator for health check
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized
