spring.application.name=shorturl

server.port=8080

# URL kết nối tới DB (thay 'semv_db' bằng tên database của bạn)
spring.datasource.url=jdbc:mysql://localhost:3306/roadtosemv?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cấu hình Hibernate / JPA
# update: Tự động cập nhật bảng dựa trên Entity; create: Xóa đi tạo lại từ đầu khi restart
spring.jpa.hibernate.ddl-auto=update
# Hiển thị câu lệnh SQL ra console để tiện debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Sử dụng trực tiếp chuỗi URL External được Render cung cấp
spring.data.redis.url=rediss://red-d860bl8js32c73ar6gqg:jSqcimbrK3Ik8zzkWHXpsLuqCFHJVWop@singapore-keyvalue.render.com:6379

system.url =localhost:8080/