spring.application.name=shorturl

server.port=8080

# --- CẤU HÌNH DATABASE POSTGRESQL (ĐÃ SỬA PASSWORD CHUẨN) ---
spring.datasource.url=jdbc:postgresql://dpg-d8ciba77f7vs73d7d7hg-a.singapore-postgres.render.com/roadtosemv_db
spring.datasource.username=roadtosemv_db_user
spring.datasource.password=BVbwaravbLJhU9wUrHG4OEQwo6eGPp8j
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis từ Render
spring.data.redis.url=rediss://red-d860bl8js32c73ar6gqg:jSqcimbrK3Ik8zzkWHXpsLuqCFHJVWop@singapore-keyvalue.render.com:6379

system.url=https://roadtosemv.onrender.com:8080/

# Actuator for health check
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized